export type AdminNavGroupKey = "overview" | "content" | "ops" | "settings";

export const adminNavigation = [
  {
    label: "الرئيسية",
    labelEn: "Dashboard",
    href: "/admin",
    description: "نظرة تشغيلية",
    descriptionEn: "Operational overview",
    group: "overview" as AdminNavGroupKey,
  },
  {
    label: "مركز المحتوى",
    labelEn: "Content Hub",
    href: "/admin/content",
    description: "ربط الأقسام والخدمات والأطباء والأجهزة",
    descriptionEn: "Unified content relationships",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "الخدمات",
    labelEn: "Services",
    href: "/admin/services",
    description: "إدارة مكتبة الخدمات",
    descriptionEn: "Manage service library",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "أقسام الخدمات",
    labelEn: "Service Categories",
    href: "/admin/service-categories",
    description: "تنظيم الخدمات داخل أقسام",
    descriptionEn: "Organize services into sections",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "الأطباء",
    labelEn: "Doctors",
    href: "/admin/doctors",
    description: "إدارة ملفات الأطباء",
    descriptionEn: "Manage doctor profiles",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "الأجهزة",
    labelEn: "Devices",
    href: "/admin/devices",
    description: "إدارة الأجهزة المعتمدة",
    descriptionEn: "Manage approved devices",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "المعرض",
    labelEn: "Gallery",
    href: "/admin/gallery",
    description: "قبل/بعد و SEO",
    descriptionEn: "Before/after and SEO",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "المجلة",
    labelEn: "Journal",
    href: "/admin/journal",
    description: "إدارة المقالات الطبية",
    descriptionEn: "Manage medical articles",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "الميديا",
    labelEn: "Media",
    href: "/admin/media",
    description: "رفع ومعاينة الصور",
    descriptionEn: "Upload and review images",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "صفحات مخصصة",
    labelEn: "Custom Pages",
    href: "/admin/pages",
    description: "صفحات خارجية بـ HTML",
    descriptionEn: "Standalone HTML pages",
    group: "content" as AdminNavGroupKey,
  },
  {
    label: "الإحصائيات",
    labelEn: "Analytics",
    href: "/admin/stats",
    description: "إحصائيات الموقع والزوار",
    descriptionEn: "Site stats and visitors",
    group: "ops" as AdminNavGroupKey,
  },
  {
    label: "الطلبات",
    labelEn: "CRM",
    href: "/admin/crm",
    description: "طلبات التواصل والمتابعة",
    descriptionEn: "Leads and follow-up",
    group: "ops" as AdminNavGroupKey,
  },
  {
    label: "ويب هوكس",
    labelEn: "Webhooks",
    href: "/admin/webhooks",
    description: "استقبال leads من فورمات خارجية",
    descriptionEn: "Receive leads from external forms",
    group: "ops" as AdminNavGroupKey,
  },
  {
    label: "السجلات",
    labelEn: "Logs",
    href: "/admin/logs",
    description: "أخطاء وتحليلات",
    descriptionEn: "Errors and analytics",
    group: "ops" as AdminNavGroupKey,
  },
  {
    label: "الصيانة",
    labelEn: "Maintenance",
    href: "/admin/maintenance",
    description: "النسخ الاحتياطية والصيانة العامة",
    descriptionEn: "Backups and maintenance",
    group: "ops" as AdminNavGroupKey,
  },
  {
    label: "المستخدمون",
    labelEn: "Users",
    href: "/admin/users",
    description: "إدارة الحسابات والصلاحيات",
    descriptionEn: "Accounts and roles",
    group: "settings" as AdminNavGroupKey,
  },
  {
    label: "الإعدادات",
    labelEn: "Settings",
    href: "/admin/settings",
    description: "هوية وتكاملات",
    descriptionEn: "Brand and integrations",
    group: "settings" as AdminNavGroupKey,
  },
] as const;
