"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";

import {
  ABOUT_PROFILE_DEFAULTS,
  ABOUT_SECTION_DEFAULTS,
} from "@/lib/about-content";
import { saveSettingsGroup } from "@/lib/content-repository";

export type SettingsActionState = {
  status: "idle" | "success" | "error";
  message: string;
};

const settingsSchema = z.object({
  phone: z.string().min(5),
  phoneSecondary: z.string().min(5),
  email: z.string().email(),
  emailSecondary: z.string().email(),
  domain: z
    .string()
    .min(4)
    .regex(
      /^[a-z0-9.-]+\.[a-z]{2,}$/i,
      "النطاق غير صالح، يجب أن يكون مثل rejuvera.sa",
    ),
  whatsapp: z.string().min(5),
  addressAr: z.string().min(5),
  addressEn: z.string().min(5),
  // hours block - subagent #3
  hoursWeekdays: z.string().min(5, "ساعات العمل الأساسية مطلوبة"),
  hoursWeekend: z.string().optional().or(z.literal("")),
  hoursWeekdaysEn: z.string().min(5, "English working hours are required"),
  hoursWeekendEn: z.string().optional().or(z.literal("")),
  faq1QuestionAr: z.string().min(3),
  faq1AnswerAr: z.string().min(10),
  faq1QuestionEn: z.string().min(3),
  faq1AnswerEn: z.string().min(10),
  faq2QuestionAr: z.string().min(3),
  faq2AnswerAr: z.string().min(10),
  faq2QuestionEn: z.string().min(3),
  faq2AnswerEn: z.string().min(10),
  faq3QuestionAr: z.string().min(3),
  faq3AnswerAr: z.string().min(10),
  faq3QuestionEn: z.string().min(3),
  faq3AnswerEn: z.string().min(10),
  faq4QuestionAr: z.string().min(3),
  faq4AnswerAr: z.string().min(10),
  faq4QuestionEn: z.string().min(3),
  faq4AnswerEn: z.string().min(10),
  faq5QuestionAr: z.string().min(3),
  faq5AnswerAr: z.string().min(10),
  faq5QuestionEn: z.string().min(3),
  faq5AnswerEn: z.string().min(10),
  siteName: z.string().min(2),
  shortName: z.string().min(2),
  tagline: z.string().min(3),
  announcement: z.string().min(3),
  seoDescription: z.string().min(20),
  logoAlt: z.string().min(5),
  brandLogo: z.string().min(5),
  brandMark: z.string().min(5),
  favicon: z.string().min(5),
  appleIcon: z.string().min(5),
  ogImage: z.string().min(5),
  homeHero: z.string().min(5),
  heroCard1: z.string().min(5),
  heroCard2: z.string().min(5),
  heroCard3: z.string().min(5),
  doctorsHero: z.string().min(5),
  servicesHero: z.string().min(5),
  aboutHero: z.string().min(5),
  journalHero: z.string().min(5),
  heroTitle: z.string().min(10),
  heroTitleAccent: z.string().min(2),
  heroDescription: z.string().min(20),
  heroPillLabel: z.string().min(2),
  heroCtaPrimary: z.string().min(3),
  heroCtaSecondary: z.string().min(3),
  trustEyebrow: z.string().min(2),
  trustTitle: z.string().min(5),
  trustDescription: z.string().min(10),
  stripEyebrow: z.string().min(2),
  stripTitle: z.string().min(5),
  stripDescription: z.string().min(10),
  galleryEyebrow: z.string().min(2),
  galleryTitle: z.string().min(10),
  galleryDescription: z.string().min(20),
  galleryItem1Image: z.string().min(5),
  galleryItem1Title: z.string().min(2),
  galleryItem1Description: z.string().min(10),
  galleryItem2Image: z.string().min(5),
  galleryItem2Title: z.string().min(2),
  galleryItem2Description: z.string().min(10),
  galleryItem3Image: z.string().min(5),
  galleryItem3Title: z.string().min(2),
  galleryItem3Description: z.string().min(10),
  quotesEyebrow: z.string().min(2),
  quotesTitle: z.string().min(10),
  quotesDescription: z.string().min(20),
  testimonial1AuthorAr: z.string().min(2),
  testimonial1AuthorEn: z.string().min(2),
  testimonial1QuoteAr: z.string().min(10),
  testimonial1QuoteEn: z.string().min(10),
  testimonial1Avatar: z.string().min(5),
  testimonial2AuthorAr: z.string().min(2),
  testimonial2AuthorEn: z.string().min(2),
  testimonial2QuoteAr: z.string().min(10),
  testimonial2QuoteEn: z.string().min(10),
  testimonial2Avatar: z.string().min(5),
  testimonial3AuthorAr: z.string().min(2),
  testimonial3AuthorEn: z.string().min(2),
  testimonial3QuoteAr: z.string().min(10),
  testimonial3QuoteEn: z.string().min(10),
  testimonial3Avatar: z.string().min(5),
  aboutEyebrowAr: z.string(),
  aboutEyebrowEn: z.string(),
  aboutTitleAr: z.string(),
  aboutTitleEn: z.string(),
  aboutDescriptionAr: z.string(),
  aboutDescriptionEn: z.string(),
  ceoVisible: z.enum(["true", "false"]),
  ceoImageUrl: z.string(),
  ceoNameAr: z.string(),
  ceoNameEn: z.string(),
  ceoTitleAr: z.string(),
  ceoTitleEn: z.string(),
  ceoDescriptionAr: z.string(),
  ceoDescriptionEn: z.string(),
  gmVisible: z.enum(["true", "false"]),
  gmImageUrl: z.string(),
  gmNameAr: z.string(),
  gmNameEn: z.string(),
  gmTitleAr: z.string(),
  gmTitleEn: z.string(),
  gmDescriptionAr: z.string(),
  gmDescriptionEn: z.string(),
  medicalTeamVisible: z.enum(["true", "false"]),
  medicalTeamImageUrl: z.string(),
  medicalTeamNameAr: z.string(),
  medicalTeamNameEn: z.string(),
  medicalTeamTitleAr: z.string(),
  medicalTeamTitleEn: z.string(),
  medicalTeamDescriptionAr: z.string(),
  medicalTeamDescriptionEn: z.string(),
  nursingTeamVisible: z.enum(["true", "false"]),
  nursingTeamImageUrl: z.string(),
  nursingTeamNameAr: z.string(),
  nursingTeamNameEn: z.string(),
  nursingTeamTitleAr: z.string(),
  nursingTeamTitleEn: z.string(),
  nursingTeamDescriptionAr: z.string(),
  nursingTeamDescriptionEn: z.string(),
  socialInstagram: z.string(),
  socialTwitter: z.string(),
  socialSnapchat: z.string(),
  socialTiktok: z.string(),
  socialYoutube: z.string(),
  socialLinkedin: z.string(),
});

export async function saveSettingsAction(
  _previousState: SettingsActionState,
  formData: FormData,
): Promise<SettingsActionState> {
  const field = (name: string, fallback?: string) => {
    const value = formData.get(name);
    return typeof value === "string" && value.trim() ? value : (fallback ?? "");
  };
  const checked = (name: string) =>
    formData.getAll(name).includes("true") ? "true" : "false";
  const aboutDefault = (key: string) =>
    ABOUT_PROFILE_DEFAULTS.find((profile) => profile.key === key);

  const parsed = settingsSchema.safeParse({
    phone: formData.get("phone"),
    phoneSecondary: formData.get("phoneSecondary"),
    email: formData.get("email"),
    emailSecondary: formData.get("emailSecondary"),
    domain: formData.get("domain"),
    whatsapp: formData.get("whatsapp"),
    addressAr: formData.get("addressAr"),
    addressEn: formData.get("addressEn"),
    hoursWeekdays: formData.get("hoursWeekdays"),
    hoursWeekend: formData.get("hoursWeekend"),
    hoursWeekdaysEn: formData.get("hoursWeekdaysEn"),
    hoursWeekendEn: formData.get("hoursWeekendEn"),
    faq1QuestionAr: formData.get("faq1QuestionAr"),
    faq1AnswerAr: formData.get("faq1AnswerAr"),
    faq1QuestionEn: formData.get("faq1QuestionEn"),
    faq1AnswerEn: formData.get("faq1AnswerEn"),
    faq2QuestionAr: formData.get("faq2QuestionAr"),
    faq2AnswerAr: formData.get("faq2AnswerAr"),
    faq2QuestionEn: formData.get("faq2QuestionEn"),
    faq2AnswerEn: formData.get("faq2AnswerEn"),
    faq3QuestionAr: formData.get("faq3QuestionAr"),
    faq3AnswerAr: formData.get("faq3AnswerAr"),
    faq3QuestionEn: formData.get("faq3QuestionEn"),
    faq3AnswerEn: formData.get("faq3AnswerEn"),
    faq4QuestionAr: formData.get("faq4QuestionAr"),
    faq4AnswerAr: formData.get("faq4AnswerAr"),
    faq4QuestionEn: formData.get("faq4QuestionEn"),
    faq4AnswerEn: formData.get("faq4AnswerEn"),
    faq5QuestionAr: formData.get("faq5QuestionAr"),
    faq5AnswerAr: formData.get("faq5AnswerAr"),
    faq5QuestionEn: formData.get("faq5QuestionEn"),
    faq5AnswerEn: formData.get("faq5AnswerEn"),
    siteName: formData.get("siteName"),
    shortName: formData.get("shortName"),
    tagline: formData.get("tagline"),
    announcement: formData.get("announcement"),
    seoDescription: formData.get("seoDescription"),
    logoAlt: formData.get("logoAlt"),
    brandLogo: formData.get("brandLogo"),
    brandMark: formData.get("brandMark"),
    favicon: formData.get("favicon"),
    appleIcon: formData.get("appleIcon"),
    ogImage: formData.get("ogImage"),
    homeHero: formData.get("homeHero"),
    heroCard1: formData.get("heroCard1"),
    heroCard2: formData.get("heroCard2"),
    heroCard3: formData.get("heroCard3"),
    doctorsHero: formData.get("doctorsHero"),
    servicesHero: formData.get("servicesHero"),
    aboutHero: formData.get("aboutHero"),
    journalHero: formData.get("journalHero"),
    heroTitle: formData.get("heroTitle"),
    heroTitleAccent: formData.get("heroTitleAccent"),
    heroDescription: formData.get("heroDescription"),
    heroPillLabel: formData.get("heroPillLabel"),
    heroCtaPrimary: formData.get("heroCtaPrimary"),
    heroCtaSecondary: formData.get("heroCtaSecondary"),
    trustEyebrow: formData.get("trustEyebrow"),
    trustTitle: formData.get("trustTitle"),
    trustDescription: formData.get("trustDescription"),
    stripEyebrow: formData.get("stripEyebrow"),
    stripTitle: formData.get("stripTitle"),
    stripDescription: formData.get("stripDescription"),
    galleryEyebrow: formData.get("galleryEyebrow"),
    galleryTitle: formData.get("galleryTitle"),
    galleryDescription: formData.get("galleryDescription"),
    galleryItem1Image: formData.get("galleryItem1Image"),
    galleryItem1Title: formData.get("galleryItem1Title"),
    galleryItem1Description: formData.get("galleryItem1Description"),
    galleryItem2Image: formData.get("galleryItem2Image"),
    galleryItem2Title: formData.get("galleryItem2Title"),
    galleryItem2Description: formData.get("galleryItem2Description"),
    galleryItem3Image: formData.get("galleryItem3Image"),
    galleryItem3Title: formData.get("galleryItem3Title"),
    galleryItem3Description: formData.get("galleryItem3Description"),
    quotesEyebrow: formData.get("quotesEyebrow"),
    quotesTitle: formData.get("quotesTitle"),
    quotesDescription: formData.get("quotesDescription"),
    testimonial1AuthorAr: formData.get("testimonial1AuthorAr"),
    testimonial1AuthorEn: formData.get("testimonial1AuthorEn"),
    testimonial1QuoteAr: formData.get("testimonial1QuoteAr"),
    testimonial1QuoteEn: formData.get("testimonial1QuoteEn"),
    testimonial1Avatar: formData.get("testimonial1Avatar"),
    testimonial2AuthorAr: formData.get("testimonial2AuthorAr"),
    testimonial2AuthorEn: formData.get("testimonial2AuthorEn"),
    testimonial2QuoteAr: formData.get("testimonial2QuoteAr"),
    testimonial2QuoteEn: formData.get("testimonial2QuoteEn"),
    testimonial2Avatar: formData.get("testimonial2Avatar"),
    testimonial3AuthorAr: formData.get("testimonial3AuthorAr"),
    testimonial3AuthorEn: formData.get("testimonial3AuthorEn"),
    testimonial3QuoteAr: formData.get("testimonial3QuoteAr"),
    testimonial3QuoteEn: formData.get("testimonial3QuoteEn"),
    testimonial3Avatar: formData.get("testimonial3Avatar"),
    aboutEyebrowAr: field(
      "aboutEyebrowAr",
      ABOUT_SECTION_DEFAULTS.eyebrowAr,
    ),
    aboutEyebrowEn: field(
      "aboutEyebrowEn",
      ABOUT_SECTION_DEFAULTS.eyebrowEn,
    ),
    aboutTitleAr: field("aboutTitleAr", ABOUT_SECTION_DEFAULTS.titleAr),
    aboutTitleEn: field("aboutTitleEn", ABOUT_SECTION_DEFAULTS.titleEn),
    aboutDescriptionAr: field(
      "aboutDescriptionAr",
      ABOUT_SECTION_DEFAULTS.descriptionAr,
    ),
    aboutDescriptionEn: field(
      "aboutDescriptionEn",
      ABOUT_SECTION_DEFAULTS.descriptionEn,
    ),
    ceoVisible: checked("ceoVisible"),
    ceoImageUrl: field("ceoImageUrl", aboutDefault("ceo")?.imageUrl),
    ceoNameAr: field("ceoNameAr", aboutDefault("ceo")?.nameAr),
    ceoNameEn: field("ceoNameEn", aboutDefault("ceo")?.nameEn),
    ceoTitleAr: field("ceoTitleAr", aboutDefault("ceo")?.titleAr),
    ceoTitleEn: field("ceoTitleEn", aboutDefault("ceo")?.titleEn),
    ceoDescriptionAr: field(
      "ceoDescriptionAr",
      aboutDefault("ceo")?.descriptionAr,
    ),
    ceoDescriptionEn: field(
      "ceoDescriptionEn",
      aboutDefault("ceo")?.descriptionEn,
    ),
    gmVisible: checked("gmVisible"),
    gmImageUrl: field("gmImageUrl", aboutDefault("gm")?.imageUrl),
    gmNameAr: field("gmNameAr", aboutDefault("gm")?.nameAr),
    gmNameEn: field("gmNameEn", aboutDefault("gm")?.nameEn),
    gmTitleAr: field("gmTitleAr", aboutDefault("gm")?.titleAr),
    gmTitleEn: field("gmTitleEn", aboutDefault("gm")?.titleEn),
    gmDescriptionAr: field(
      "gmDescriptionAr",
      aboutDefault("gm")?.descriptionAr,
    ),
    gmDescriptionEn: field(
      "gmDescriptionEn",
      aboutDefault("gm")?.descriptionEn,
    ),
    medicalTeamVisible: checked("medicalTeamVisible"),
    medicalTeamImageUrl: field(
      "medicalTeamImageUrl",
      aboutDefault("medicalTeam")?.imageUrl,
    ),
    medicalTeamNameAr: field(
      "medicalTeamNameAr",
      aboutDefault("medicalTeam")?.nameAr,
    ),
    medicalTeamNameEn: field(
      "medicalTeamNameEn",
      aboutDefault("medicalTeam")?.nameEn,
    ),
    medicalTeamTitleAr: field(
      "medicalTeamTitleAr",
      aboutDefault("medicalTeam")?.titleAr,
    ),
    medicalTeamTitleEn: field(
      "medicalTeamTitleEn",
      aboutDefault("medicalTeam")?.titleEn,
    ),
    medicalTeamDescriptionAr: field(
      "medicalTeamDescriptionAr",
      aboutDefault("medicalTeam")?.descriptionAr,
    ),
    medicalTeamDescriptionEn: field(
      "medicalTeamDescriptionEn",
      aboutDefault("medicalTeam")?.descriptionEn,
    ),
    nursingTeamVisible: checked("nursingTeamVisible"),
    nursingTeamImageUrl: field(
      "nursingTeamImageUrl",
      aboutDefault("nursingTeam")?.imageUrl,
    ),
    nursingTeamNameAr: field(
      "nursingTeamNameAr",
      aboutDefault("nursingTeam")?.nameAr,
    ),
    nursingTeamNameEn: field(
      "nursingTeamNameEn",
      aboutDefault("nursingTeam")?.nameEn,
    ),
    nursingTeamTitleAr: field(
      "nursingTeamTitleAr",
      aboutDefault("nursingTeam")?.titleAr,
    ),
    nursingTeamTitleEn: field(
      "nursingTeamTitleEn",
      aboutDefault("nursingTeam")?.titleEn,
    ),
    nursingTeamDescriptionAr: field(
      "nursingTeamDescriptionAr",
      aboutDefault("nursingTeam")?.descriptionAr,
    ),
    nursingTeamDescriptionEn: field(
      "nursingTeamDescriptionEn",
      aboutDefault("nursingTeam")?.descriptionEn,
    ),
    socialInstagram: formData.get("socialInstagram") ?? "",
    socialTwitter: formData.get("socialTwitter") ?? "",
    socialSnapchat: formData.get("socialSnapchat") ?? "",
    socialTiktok: formData.get("socialTiktok") ?? "",
    socialYoutube: formData.get("socialYoutube") ?? "",
    socialLinkedin: formData.get("socialLinkedin") ?? "",
  });

  if (!parsed.success) {
    return {
      status: "error",
      message: "بيانات الإعدادات غير مكتملة أو غير صحيحة.",
    };
  }

  const [
    contactResult,
    brandResult,
    mediaResult,
    homepageResult,
    aboutResult,
    socialResult,
  ] = await Promise.all([
    saveSettingsGroup("contact", {
      phone: parsed.data.phone,
      phoneSecondary: parsed.data.phoneSecondary,
      email: parsed.data.email,
      emailSecondary: parsed.data.emailSecondary,
      domain: parsed.data.domain,
      whatsapp: parsed.data.whatsapp,
      addressAr: parsed.data.addressAr,
      addressEn: parsed.data.addressEn,
      // hours block - subagent #3
      hoursWeekdays: parsed.data.hoursWeekdays,
      hoursWeekend: parsed.data.hoursWeekend ?? "",
      hoursWeekdaysEn: parsed.data.hoursWeekdaysEn,
      hoursWeekendEn: parsed.data.hoursWeekendEn ?? "",
      faq1QuestionAr: parsed.data.faq1QuestionAr,
      faq1AnswerAr: parsed.data.faq1AnswerAr,
      faq1QuestionEn: parsed.data.faq1QuestionEn,
      faq1AnswerEn: parsed.data.faq1AnswerEn,
      faq2QuestionAr: parsed.data.faq2QuestionAr,
      faq2AnswerAr: parsed.data.faq2AnswerAr,
      faq2QuestionEn: parsed.data.faq2QuestionEn,
      faq2AnswerEn: parsed.data.faq2AnswerEn,
      faq3QuestionAr: parsed.data.faq3QuestionAr,
      faq3AnswerAr: parsed.data.faq3AnswerAr,
      faq3QuestionEn: parsed.data.faq3QuestionEn,
      faq3AnswerEn: parsed.data.faq3AnswerEn,
      faq4QuestionAr: parsed.data.faq4QuestionAr,
      faq4AnswerAr: parsed.data.faq4AnswerAr,
      faq4QuestionEn: parsed.data.faq4QuestionEn,
      faq4AnswerEn: parsed.data.faq4AnswerEn,
      faq5QuestionAr: parsed.data.faq5QuestionAr,
      faq5AnswerAr: parsed.data.faq5AnswerAr,
      faq5QuestionEn: parsed.data.faq5QuestionEn,
      faq5AnswerEn: parsed.data.faq5AnswerEn,
    }),
    saveSettingsGroup("brand", {
      siteName: parsed.data.siteName,
      shortName: parsed.data.shortName,
      tagline: parsed.data.tagline,
      announcement: parsed.data.announcement,
      seoDescription: parsed.data.seoDescription,
      logoAlt: parsed.data.logoAlt,
    }),
    saveSettingsGroup("media", {
      brandLogo: parsed.data.brandLogo,
      brandMark: parsed.data.brandMark,
      favicon: parsed.data.favicon,
      appleIcon: parsed.data.appleIcon,
      ogImage: parsed.data.ogImage,
      homeHero: parsed.data.homeHero,
      heroCard1: parsed.data.heroCard1,
      heroCard2: parsed.data.heroCard2,
      heroCard3: parsed.data.heroCard3,
      doctorsHero: parsed.data.doctorsHero,
      servicesHero: parsed.data.servicesHero,
      aboutHero: parsed.data.aboutHero,
      journalHero: parsed.data.journalHero,
    }),
    saveSettingsGroup("homepage", {
      heroTitle: parsed.data.heroTitle,
      heroTitleAccent: parsed.data.heroTitleAccent,
      heroDescription: parsed.data.heroDescription,
      heroPillLabel: parsed.data.heroPillLabel,
      heroCtaPrimary: parsed.data.heroCtaPrimary,
      heroCtaSecondary: parsed.data.heroCtaSecondary,
      trustEyebrow: parsed.data.trustEyebrow,
      trustTitle: parsed.data.trustTitle,
      trustDescription: parsed.data.trustDescription,
      stripEyebrow: parsed.data.stripEyebrow,
      stripTitle: parsed.data.stripTitle,
      stripDescription: parsed.data.stripDescription,
      galleryEyebrow: parsed.data.galleryEyebrow,
      galleryTitle: parsed.data.galleryTitle,
      galleryDescription: parsed.data.galleryDescription,
      galleryItem1Image: parsed.data.galleryItem1Image,
      galleryItem1Title: parsed.data.galleryItem1Title,
      galleryItem1Description: parsed.data.galleryItem1Description,
      galleryItem2Image: parsed.data.galleryItem2Image,
      galleryItem2Title: parsed.data.galleryItem2Title,
      galleryItem2Description: parsed.data.galleryItem2Description,
      galleryItem3Image: parsed.data.galleryItem3Image,
      galleryItem3Title: parsed.data.galleryItem3Title,
      galleryItem3Description: parsed.data.galleryItem3Description,
      quotesEyebrow: parsed.data.quotesEyebrow,
      quotesTitle: parsed.data.quotesTitle,
      quotesDescription: parsed.data.quotesDescription,
      testimonial1AuthorAr: parsed.data.testimonial1AuthorAr,
      testimonial1AuthorEn: parsed.data.testimonial1AuthorEn,
      testimonial1QuoteAr: parsed.data.testimonial1QuoteAr,
      testimonial1QuoteEn: parsed.data.testimonial1QuoteEn,
      testimonial1Avatar: parsed.data.testimonial1Avatar,
      testimonial2AuthorAr: parsed.data.testimonial2AuthorAr,
      testimonial2AuthorEn: parsed.data.testimonial2AuthorEn,
      testimonial2QuoteAr: parsed.data.testimonial2QuoteAr,
      testimonial2QuoteEn: parsed.data.testimonial2QuoteEn,
      testimonial2Avatar: parsed.data.testimonial2Avatar,
      testimonial3AuthorAr: parsed.data.testimonial3AuthorAr,
      testimonial3AuthorEn: parsed.data.testimonial3AuthorEn,
      testimonial3QuoteAr: parsed.data.testimonial3QuoteAr,
      testimonial3QuoteEn: parsed.data.testimonial3QuoteEn,
      testimonial3Avatar: parsed.data.testimonial3Avatar,
    }),
    saveSettingsGroup("about", {
      eyebrowAr: parsed.data.aboutEyebrowAr,
      eyebrowEn: parsed.data.aboutEyebrowEn,
      titleAr: parsed.data.aboutTitleAr,
      titleEn: parsed.data.aboutTitleEn,
      descriptionAr: parsed.data.aboutDescriptionAr,
      descriptionEn: parsed.data.aboutDescriptionEn,
      ceoVisible: parsed.data.ceoVisible,
      ceoImageUrl: parsed.data.ceoImageUrl,
      ceoNameAr: parsed.data.ceoNameAr,
      ceoNameEn: parsed.data.ceoNameEn,
      ceoTitleAr: parsed.data.ceoTitleAr,
      ceoTitleEn: parsed.data.ceoTitleEn,
      ceoDescriptionAr: parsed.data.ceoDescriptionAr,
      ceoDescriptionEn: parsed.data.ceoDescriptionEn,
      gmVisible: parsed.data.gmVisible,
      gmImageUrl: parsed.data.gmImageUrl,
      gmNameAr: parsed.data.gmNameAr,
      gmNameEn: parsed.data.gmNameEn,
      gmTitleAr: parsed.data.gmTitleAr,
      gmTitleEn: parsed.data.gmTitleEn,
      gmDescriptionAr: parsed.data.gmDescriptionAr,
      gmDescriptionEn: parsed.data.gmDescriptionEn,
      medicalTeamVisible: parsed.data.medicalTeamVisible,
      medicalTeamImageUrl: parsed.data.medicalTeamImageUrl,
      medicalTeamNameAr: parsed.data.medicalTeamNameAr,
      medicalTeamNameEn: parsed.data.medicalTeamNameEn,
      medicalTeamTitleAr: parsed.data.medicalTeamTitleAr,
      medicalTeamTitleEn: parsed.data.medicalTeamTitleEn,
      medicalTeamDescriptionAr: parsed.data.medicalTeamDescriptionAr,
      medicalTeamDescriptionEn: parsed.data.medicalTeamDescriptionEn,
      nursingTeamVisible: parsed.data.nursingTeamVisible,
      nursingTeamImageUrl: parsed.data.nursingTeamImageUrl,
      nursingTeamNameAr: parsed.data.nursingTeamNameAr,
      nursingTeamNameEn: parsed.data.nursingTeamNameEn,
      nursingTeamTitleAr: parsed.data.nursingTeamTitleAr,
      nursingTeamTitleEn: parsed.data.nursingTeamTitleEn,
      nursingTeamDescriptionAr: parsed.data.nursingTeamDescriptionAr,
      nursingTeamDescriptionEn: parsed.data.nursingTeamDescriptionEn,
    }),
    saveSettingsGroup("social", {
      instagram: parsed.data.socialInstagram,
      twitter: parsed.data.socialTwitter,
      snapchat: parsed.data.socialSnapchat,
      tiktok: parsed.data.socialTiktok,
      youtube: parsed.data.socialYoutube,
      linkedin: parsed.data.socialLinkedin,
    }),
  ]);

  revalidatePath("/admin/settings");
  revalidatePath("/admin/media");
  revalidatePath("/");
  revalidatePath("/contact");
  revalidatePath("/about");
  revalidatePath("/doctors");
  revalidatePath("/services");
  revalidatePath("/devices");
  revalidatePath("/journal");
  revalidatePath("/gallery");
  revalidatePath("/", "layout");

  return {
    status: "success",
    message:
      contactResult.mode === "database" &&
      brandResult.mode === "database" &&
      mediaResult.mode === "database" &&
      homepageResult.mode === "database" &&
      aboutResult.mode === "database" &&
      socialResult.mode === "database"
        ? "تم حفظ الإعدادات واعتمادها على الواجهة بنجاح."
        : "تم تحديث الإعدادات داخل بيئة العمل الحالية بنجاح.",
  };
}
